apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-node-app-deployment
  labels:
    app: {{ .Release.Name }}-node-app
spec:
  replicas: {{ .Values.nodeApp.replicaCount | default .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-node-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-node-app
    spec:
      containers:
        - name: node-app
          image: "{{ .Values.nodeApp.image.repository }}:{{ .Values.nodeApp.image.tag }}"
          ports:
            - containerPort: {{ .Values.nodeApp.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 14 }}
