apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-node-app-service
spec:
  type: {{ .Values.nodeApp.service.type }}
  selector:
    app: {{ .Release.Name }}-node-app
  ports:
    - protocol: TCP
      port: {{ .Values.nodeApp.service.port }}
      targetPort: {{ .Values.nodeApp.service.port }}
