apiVersion: v1
kind: Service
metadata:
  name: {{ include "flex-backend-chart.fullname" . }}-ai-services
  labels:
    {{- include "flex-backend-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai-services
spec:
  type: {{ .Values.aiService.service.type }}
  ports:
    - port: {{ .Values.aiService.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "flex-backend-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ai-services