apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ai-services
spec:
  type: {{ .Values.aiService.service.type }}
  selector:
    app: {{ .Release.Name }}-ai-services
  ports:
    - protocol: TCP
      port: {{ .Values.aiService.service.port }}
      targetPort: {{ .Values.aiService.service.port }}
