apiVersion: v1
kind: Service
metadata:
  name: {{ include "flex-backend-chart.fullname" . }}-llm-services
  labels:
    {{- include "flex-backend-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: llm-services
spec:
  type: {{ .Values.llmService.service.type }}
  ports:
    - port: {{ .Values.llmService.service.port }}
      targetPort: 11434
      protocol: TCP
  selector:
    {{- include "flex-backend-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: llm-services